// IMAGES ///////////////////////////////////////////////////////////////////////////
export enum Sprites {
  // ball
  ball = "ball",
  fireBall = "fireBall",
  // paddle
  paddle = "paddle",
  cannon = "cannon",
  cannonShooting = "cannonShooting",
  bullet = "bullet",
  holdBallStub = "holdBallStub",
  holdBallBolt = "holdBallBolt",
  // brick
  commonBrick = "commonBrick",
  lockedBrick = "lockedBrick",
  fireBrick = "fireBrick",
  burnBrick = "burnBrick",
  metalBrick = "metalBrick",
  blankBrick = "blankBrick",
  iceBrick = "iceBrick",
  rockBrick = "rockBrick",
  glassBrick = "glassBrick",
  grassBrick = "grassBrick",
  poisonDrop = "poisonDrop",
  leafBurst = "leafBurst",
  // powerups
  speedUpBall = "speedUpBall",
  getLife = "getLife",
  loseLife = "loseLife",
  expandPaddle = "expandPaddle",
  shrinkPaddle = "shrinkPaddle",
  igniteBall = "igniteBall",
  addShooter = "addShooter",
  notYetDiscovered = "notYetDiscovered",
  holdBall = "holdBall",
  revealInvisible = "revealInvisible",
  fallingBricks = "fallingBricks",
  // UI
  headbar = "headbar",
  heart = "heart",
  brickSelector = "brickSelector",
  brickHighlight = "brickHighlight",
  menuBox2 = "menuBox2",
  menuBox3 = "menuBox3",
  menuBox4 = "menuBox4",
  genericButton = "genericButton",
  mainButton = "mainButton",
  playButton = "playButton",
  backButton = "backButton",
  pauseButton = "pauseButton",
  clearButton = "clearButton",
  menuHanger = "menuHanger",
  languageSelectionBox = "languageSelectionBox",
  optionsBox = "optionsBox",
  arrowButton = "arrowButton",
  titleFrame = "titleFrame",
  sideBar = "sideBar",
  dot = "dot",
  dotHighlight = "dotHighlight",
  checkbox = "checkbox",
  defaultCursor = "url(assets/images/UI/cursor_default.cur), auto",
  eraserCursor = "url(assets/images/UI/cursor_eraser.cur), auto",
  pointerCursor = "url(assets/images/UI/cursor_pointer.cur) 16 16, auto",
  // volume slider
  volumeBar = "volumeBar",
  volumeNob = "volumeNob",
  // flags
  italian = "italian",
  romanian = "romanian",
  english = "english",
  flagHighlight = "flagHighlight",
  // text
  start = "start",
  restart = "restart",
  resume = "resume",
  backToMenu = "backToMenu",
  gameOver = "gameOver",
  customLevel = "customLevel",
  // others
  smoke = "smoke",
  sparkle = "sparkle",
}

// AUDIO ///////////////////////////////////////////////////////////////////////////
export enum Sounds {
  bounce = "bounce",
  brickbreak = "brickbreak",
  fireBrickbreak = "fireBrickbreak",
  shuffle = "shuffle",
  gameOver = "gameOver",
  lifeLost = "lifeLost",
  fireBrick = "fireBrick",
  buttonPress = "buttonPress",
  hitMetal = "hitMetal",
  ballIgnition = "ballIgnition",
  shot = "shot",
  holdBall = "holdBall",
  erase = "erase",
  glassShatter = "glassShatter",
  glassCrack = "glassCrack",
  spell = "spell",
  clang = "clang",
  newLife = "newLife",
  die = "die",
  reload = "reload",
  expand = "expand",
  shrink = "shrink",
  rustle = "rustle",
}

// FONTS ///////////////////////////////////////////////////////////////////////////
export enum Fonts {
  manaspace = "Manaspace",
}
